2024-04-09 11:10:39,143 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Configure stats pid to 19444
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Alexia\.config\wandb\settings
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Loading settings from c:\Users\Alexia\diffusion_ts\wandb\settings
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 11:10:39,145 INFO    MainThread:19444 [wandb_init.py:_log_setup():527] Logging user logs to c:\Users\Alexia\diffusion_ts\wandb\run-20240409_111039-jfcr2ryg\logs\debug.log
2024-04-09 11:10:39,145 INFO    MainThread:19444 [wandb_init.py:_log_setup():528] Logging internal logs to c:\Users\Alexia\diffusion_ts\wandb\run-20240409_111039-jfcr2ryg\logs\debug-internal.log
2024-04-09 11:10:39,145 INFO    MainThread:19444 [wandb_init.py:init():567] calling init triggers
2024-04-09 11:10:39,145 INFO    MainThread:19444 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-04-09 11:10:39,145 INFO    MainThread:19444 [wandb_init.py:init():592] re-initializing run, found existing run on stack: 7yghdcgc
2024-04-09 11:10:39,146 INFO    MainThread:19444 [wandb_run.py:_finish():2052] finishing run fyp_a/test_train_2/7yghdcgc
2024-04-09 11:10:39,147 ERROR   MainThread:19444 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-04-09 11:10:39,147 INFO    MainThread:19444 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-09 11:10:39,147 INFO    MainThread:19444 [wandb_init.py:_jupyter_teardown():455] cleaning up jupyter logic
2024-04-09 11:10:39,147 INFO    MainThread:19444 [wandb_run.py:_atexit_cleanup():2292] got exitcode: 0
2024-04-09 11:10:39,147 INFO    MainThread:19444 [wandb_run.py:_restore():2275] restore
2024-04-09 11:10:39,147 INFO    MainThread:19444 [wandb_run.py:_restore():2281] restore done
